name: team_guard
description: Custom lint plugin to block forbidden Flutter widgets across team projects.
version: 1.0.4
repository: https://github.com/HazemHamdy7/team_guard

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  analyzer: ">=8.4.0 <12.0.0"
  custom_lint_builder: ^0.8.1
  yaml: ^3.1.2

dev_dependencies:
  custom_lint: ^0.8.1
  lints: ^5.1.1
